# Generated by Django 4.2.6 on 2023-10-23 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('cedula', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=10)),
                ('edad', models.PositiveIntegerField()),
                ('tipo_lesion', models.CharField(default='Sin lesión', max_length=100)),
                ('rutinas_asignadas', models.PositiveIntegerField(default=0)),
                ('recomendacion', models.CharField(default='Ninguna', max_length=300)),
                ('tiempo_descanso_entre_rutinas', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppRehabilitation.doctor')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_rutina', models.PositiveIntegerField()),
                ('repeticiones_asignadas', models.PositiveIntegerField()),
                ('tiempo_descanso_repeticiones', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='AppRehabilitation.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Repeticiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('numero_repeticion', models.PositiveIntegerField()),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repeticiones', to='AppRehabilitation.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fase', models.CharField(max_length=100)),
                ('angulo_brazo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('angulo_codo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('angulo_muneca', models.DecimalField(decimal_places=2, max_digits=5)),
                ('velocidad_brazo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('velocidad_codo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('velocidad_muneca', models.DecimalField(decimal_places=2, max_digits=5)),
                ('repeticion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fases', to='AppRehabilitation.repeticiones')),
            ],
        ),
    ]
